---
title: "Loading of datasets"
format: html
editor: visual
---

# K-means clustering using PCA

Here, we want to see if we can determine the PAM50 groups using only the significant proteins from the linear models.

First, we make a PCA using the

```{r}
signif_fdr_prots <- c(HER2 |> filter(adjusted_fdr <= 0.05) |> pull(protein),
                  Luminal_A |> filter(adjusted_fdr <= 0.05) |> pull(protein), 
                  Luminal_B |> filter(adjusted_fdr <= 0.05) |> pull(protein), 
                  DGEA_Basal_like |> filter(adjusted_fdr <= 0.05) |> pull(protein))

signif_fdr_prots_unique <- unique(signif_prots)

signif_fdr_prots_unique
```

```{r}
count_matrix_reduced <- count_matrix_1 |>
  rownames_to_column("protein")|>
  filter(protein %in% signif_fdr_prots_unique) |>
  column_to_rownames("protein") |>
  t() |>
  data.frame()


pca <- count_matrix_reduced |>
  prcomp(center = TRUE,
         scale = TRUE) 

#Scree
pca  |>
  broom::tidy("pcs")|> 
  mutate(percent = percent * 100) |> 
  ggplot(aes(x = PC,
             y = percent)) +
  geom_hline(yintercept = 0) +
  geom_col(colour = "black",
           alpha = 0.5) +
  theme_bw(base_size = 20) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank()) +
  labs(title = "Scree Plot of PCA of significant proteins")


```

```{r}
pca_plot_axes_labels <- pca |>
  broom::tidy("eigenvalues") |>
  mutate(lbl = str_c("PC", PC, ", VE = ", round(percent*100,2), "%")) |> 
  pull("lbl")
```

```{r}

clinical_data <- clinical_data |>
  rename(id = "Complete TCGA ID", PAM50 = "PAM50 mRNA")

pca_aug <- pca |>
  broom::augment(count_matrix_reduced) |>
  rename(id = ".rownames") |>
  left_join(clinical_data |>  select(c(id, PAM50)),
            by = "id") 

pca_plot <- pca_aug |> 
  ggplot(aes(x = .fittedPC1,
             y = .fittedPC2,
             colour = PAM50,
             fill = PAM50)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point(shape = 21,
             size = 6,
             alpha = 0.5) +
  theme_bw(base_size = 20,
           base_family = "avenir") +
  labs(
    title = "PCA",
    x = pluck(pca_plot_axes_labels, 1),
    y = pluck(pca_plot_axes_labels, 2))

pca_plot

```

Now, we run the k-means algorithm using n = 4, as we have 4 groups we want to determine:

```{r}
k_means_data <- pca_aug |>
  select(c(.fittedPC1, .fittedPC2)) 

kmeans(k_means_data, centers = 4)
```
