---
title: "Loading of datasets"
format: html
editor: visual
---

# Introduction to the dataset

# Is the dataset tidy?

## Loading of dataset

```{r}
#| label: load packages and data
rm(list = ls())
library(curl)
library(tidyverse)
library("quarto")
protein_data <- read_csv2("../_raw/77_cancer_proteomes_CPTAC_itraq.csv")
clinical_data <- read_csv2("../_raw/clinical_data_breast_cancer.csv")
PAM50_file <- read_csv2("../_raw/PAM50_proteins.csv")
```

```{r}
#| label: write data to csv file
#write_csv2 converts the count matrix to a variable of characters
write_csv2(protein_data, "../data/protein_load.csv")
write_csv2(clinical_data, "../data/clinical_load.csv")
write_csv2(PAM50_file, "../data/PAM50_load.csv")
```

```{r}
<<<<<<< HEAD
 #| label: quarto rendering
#quarto::quarto_render("01_load_DONE.qmd",output_format = "html")
#file.rename(from = "01_load_DONE.html",
#            to = "../results/01_load.html")
```

```{r}
=======
>>>>>>> 41af585a339fb32094b34b7f5953e03725a070cc
rm(list = ls())
```
