---
title: "07_survival"
format: html
editor: visual
---

```{r}
library(tidyverse)

HER2 <- read.table("../data/diff_exp_HER2.tsv", header = T, sep = "\t") |>
  select(c(protein, estimate, adjusted_fdr)) |>
  rename(estimate_HER2 = estimate, adjustedfdr_HER2 = adjusted_fdr)

lumA <- read.table("../data/diff_exp_Luminal_A.tsv", header = T, sep = "\t")|>
  select(c(protein, estimate, adjusted_fdr)) |>
  rename(estimate_lumA = estimate, adjustedfdr_lumA = adjusted_fdr)

lumB <- read.table("../data/diff_exp_Luminal_B.tsv", header = T, sep = "\t")|>
  select(c(protein, estimate, adjusted_fdr)) |>
  rename(estimate_lumB = estimate, adjustedfdr_lumB = adjusted_fdr)

basal_like <- read.table("../data/diff_exp_Basal_like.tsv", header = T, sep = "\t")|>
  select(c(protein, estimate, adjusted_fdr))|>
  rename(estimate_bl = estimate, adjustedfdr_bl = adjusted_fdr)

signif_fdr_prots <- c(HER2 |> filter(adjustedfdr_HER2 <= 0.05) |> pull(protein),
                  lumA |> filter(adjustedfdr_lumA <= 0.05) |> pull(protein), 
                  lumB |> filter(adjustedfdr_lumB <= 0.05) |> pull(protein), 
                  basal_like |> filter(adjustedfdr_bl <= 0.05) |> pull(protein))

signif_fdr_prots_unique <- unique(signif_fdr_prots)

rm(signif_fdr_prots)
```

```{r}
combined <- left_join(HER2, lumA, by = "protein") |>
  left_join(lumB, by = "protein") |>
  left_join(basal_like, by = "protein") |>
  filter(protein %in% signif_fdr_prots_unique) |>
  arrange(desc(adjustedfdr_bl)) |>
  mutate(protein = factor(protein), 
         protein = fct_reorder(protein, adjustedfdr_bl))
  
rm(basal_like, lumA, lumB, HER2, signif_fdr_prots_unique)
```

```{r}
combined_long <- combined %>%
  pivot_longer(cols = -c(protein),
               names_pattern = "(.*)(..)$",
               names_to = c("pam50", ".value"),
               values_to = "estimate",
               values_drop_na = TRUE) 

combined_long <- combined %>%
  pivot_longer(cols = -protein,
               names_to = c(".value", "pam50"),
               names_sep = "_") |>
  mutate(
    pam50 = case_when(
      pam50 == "HER2" ~ "HER2 enriched", 
      pam50 == "lumA" ~ "Luminal A", 
      pam50 == "lumB" ~ "Luminal B", 
      pam50 == "bl" ~ "Basal like"),
    significance = case_when(
      adjustedfdr < 0.001 ~ "***", 
      adjustedfdr < 0.01 ~ "**",
      adjustedfdr < 0.05 ~ "*",
      TRUE ~ ""
    )
  )


```

```{r}

heatmap <- ggplot(combined_long, aes(x =pam50 , y = protein, fill = estimate))+
  geom_tile() +
  scale_fill_gradient2(midpoint = 0, low = "blue", high = "red", mid = "white") +
  labs(
    title = "Heatmap of results from differential expression analysis", 
    y = "", 
    x = "", 
    color = "Estimate"
  ) +
  geom_text(aes(x =pam50 , y = protein, label = significance), size = 4, vjust = 0.8) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5), 
        axis.text.y = element_text(size = 5), 
        panel.background = element_blank(),
        legend.position="bottom")

heatmap

ggsave("../plots/heatmap_diif_exp_analysis.png", heatmap, height = 20, width = 4, dpi = 300)
```
