---
title: "05_PCA"
format: html
editor: visual
---

```{r}
<<<<<<< HEAD
=======
#| label: define dataframe

# use this df from the 01_load 
cm <- read.table("../data/count_matrix_1_77.tsv", header = T)

```

```{r}
>>>>>>> 41c8fcefc2eb468b0732cd2ea8a4855e21a55c9a
#| echo: false
#| label: load packages

library(tidyverse)
library(broom)
library(cowplot)

```

```{r}
#| label: define countmatrix and augment

cm <- read.table("../data/count_matrix_1_77.tsv", header = T)

# flip
cm <- pivot_longer(cols = -id, names_to = 'variable', values_to = 'value') |>
  pivot_wider(names_from = id, values_from = value) |>
  rename(id = variable)
```

```{r}
#| label: define PCA

#Create a PCA object scaling the data
pca <- cm |>
        scale() |>
        prcomp()

#Extract variance explained by the PCs
pca_results <- pca |>
  tidy("pcs")

pc1var <- pca_results$percent[1]*100
pc2var <- pca_results$percent[2]*100
```

```{r}
#| label: PCA plot

# Create PCA plot
pca_plot <- pca |> 
  augment(clinical_data) |>
   ggplot(aes(x=.fittedPC1, 
              y=.fittedPC2, 
              color = pam50,
              fill = pam50)) +
   geom_point(shape = 21,
             size = 2,
             alpha = 0.5) +
   theme_half_open(12) + 
   theme(plot.title = element_text(hjust = 0.5)) +
   background_grid() +
   xlab(paste('PC1,', pc1var, '% explained variance')) + 
   ylab(paste('PC2,', pc2var, '% explained variance')) +
   labs(
     title = "Initial PCA on entire proteomics dataset",
     color = "pam50"
        )
  
pca_plot
```

Another attempt but so far not working:

```{r}


# Create PCA plot
pca_aug <- pca |> 
  broom::augment(t_count) |>
  rename(id = ".rownames") |>
  left_join(clinical_data |> select(c(id, PAM50)),
            by = "id")

pca_plot <- pca_aug |>
   ggplot(aes(x=.fittedPC1, 
              y=.fittedPC2, 
              color = `PAM50`)) +
   geom_point(size = 1.5) +
   theme_half_open(12) + 
   
   theme(plot.title = element_text(hjust = 0.5)) +
   background_grid() +
   xlab(paste('PC1,', pc1var, '% explained variance')) + 
   ylab(paste('PC2,', pc2var, '% explained variance')) +
   labs(
     title = "Initial PCA on entire proteomics dataset",
     color = "PAM50"
        )
  
pca_plot
```
